spring:
  application:
    name: security

  profiles:
    active: dev

  devtools:
    restart:
      enabled: true

    livereload:
      enabled: true

  security:
    user:
      name: jjang051
      password: 1234
      roles: ADMIN

mybatis:
  config-location: classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml